name: "ZAP to SARIF format file"
description: "Action to transform a ZAP JSON report into GitHub SARIF format"
inputs:
  file_in:
    description: "Path to the ZAP JSON file report"
    required: true
  file_out:
    description: "Path to the SARIF file to generate"
    required: true
outputs:
  exported_report:
    description: "Processed SARIF file"
    value: ${{ steps.run-sarif.outputs.exported_report }}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Run conversion script
      id: run-sarif
      run: |
        python main.py "${{ inputs.file_in }}" "${{ inputs.file_out }}"
        echo "exported_report=${{ inputs.file_out }}" >> "$GITHUB_OUTPUT"
      shell: bash
